name: Playwright Tests with Allure Report

on:
  schedule:
    - cron: "30 18 * * *"  # Runs daily at 6:30 PM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests with Allure
        run: |
          npx playwright test --reporter=line,allure-playwright
          echo "Playwright tests completed."

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Print Allure Report Link
        run: echo "✅ Allure Report Available at: https://naven7009.github.io/playwright-automationexercise/allure-report/"
